shaneworld/force-app/main/default/objects/YuGiOh_Card__c/YuGiOh_Card__c.object-meta.xml
<CustomObject>
    <label>YuGiOh Card</label>
    <nameField>
        <label>YuGiOh Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>YuGiOh Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

shaneworld/force-app/main/default/objects/YuGiOh_Card__c/fields/Primary_Image__c.field-meta.xml
<CustomField>
    <fullName>Primary_Image__c</fullName>
    <label>Primary Image</label>
    <type>Url</type>
</CustomField>

shaneworld/force-app/main/default/classes/CustomCardHandler.cls
public with sharing class CustomCardHandler 
{
    @InvocableMethod(label='Link Image to record')
    public static void linkImage(List<ID> recordId)
    {
        List<YuGiOh_Card__c> cardList = [SELECT Id FROM YuGiOh_Card__c WHERE Id =: recordId];
        
        for(YuGiOh_Card__c yc: cardList)
        {
        	    yc.Primary_Image__c = [SELECT ContentDocumentId, LinkedEntityId 
                                       FROM ContentDocumentLink 
                                       WHERE LinkedEntityId =: yc.Id LIMIT 1].ContentDocumentId;
        }
        
        update cardList;
    }
}
/*[SELECT Id, LinkedEntityId, ContentDocumentId, Visibility, IsDeleted, ShareType,
ContentDocument.Title, ContentDocument.createdDate, ContentDocument.FileType
FROM ContentDocumentLink 
WHERE LinkedEntityId = '<recordID>'];*/